### ISSUE TITLE
move redis client to a subpackage to prevent vendor pollution

### ISSUE THREAD

**Issue by savaki** [launchdarkly/go-client#108]
Go users are required to vendor redigo to use the launchdarkly client because redis.go is in the same package as the client.  If redis is optional, it might be nicer to put it into a separate package so it doesn't force all users of the go-client to vendor redigo.

**Comment by ashanbrown** [comment]
Thanks @savaki, this seems like a very reasonable suggestion.  I would be concerned that moving RedisFeatureStore to another package would also be a breaking change for anyone on the v2 branch.  Another option might be to separate out the code that depends on redigo and add the build tag `!launchdarkly-no-redis` to those files.  Then I think you could build without it by setting the `launchdarkly-no-redis` build tag during your build.  Would that work for your requirements?

**Comment by savaki** [comment]
Sure, that would work.

**Comment by ashanbrown** [comment]
This change should allow you to set the `launchdarkly_no_redis` build tag:

https://github.com/launchdarkly/go-client/commit/3abbdaf76e7ba2e068e65b47503c862a30a42463

Thanks again for the suggestion.  Please let us know if you have any more concerns.
