### ISSUE TITLE
Configuring the log verbosity level

### ISSUE THREAD

**Issue by nboukeffa** [launchdarkly/go-client#127]
Hi,

I'm using the v4 client. Is there anyway to configure the log verbosity level?

Regards,

**Comment by eli-darkly** [comment]
Unfortunately, there's no standard mechanism for this in the Go client. Your best bet would be to provide an implementation of the `Logger` interface in your configuration, and filter by checking for a prefix. Here's an example that will print only WARN and ERROR lines:

```
type WarnErrorLogger struct {
	wrappedLogger ld.Logger
}

func NewWarnErrorLogger(wrappedLogger ld.Logger) WarnErrorLogger {
	return WarnErrorLogger{ld.DefaultConfig.Logger}
}

func (l WarnErrorLogger) testPrefix(value interface{}) bool {
	if s, ok := value.(string); ok {
		return strings.HasPrefix(s, "WARN:") || strings.HasPrefix(s, "ERROR:")
	}
	return false
}

func (l WarnErrorLogger) Println(values ...interface{}) {
	if len(values) > 0 && l.testPrefix(values[0]) {
		l.wrappedLogger.Println(values...)
	}
}

func (l WarnErrorLogger) Printf(fmt string, values ...interface{}) {
	if l.testPrefix(fmt) {
		l.wrappedLogger.Printf(fmt, values...)
	}
}
```

You would use this in your code like so:
```
	config := ld.DefaultConfig
	config.Logger = NewWarnErrorLogger()
	client := MakeCustomClient(sdkKey, config, 5*time.Second)
```

Note that WARN and ERROR are the only levels identified in this way - anything below WARN just doesn't have a prefix.

**Comment by nboukeffa** [comment]
Thanks @eli-darkly for your answer. I'm closing the issue.
