### ISSUE TITLE
Missing log message on streaming connection failure

### ISSUE THREAD

**Issue by Drahflow** [launchdarkly/go-client#141]
**Describe the bug**
If the connection to streaming fails, the error message is not guaranteed to reach the logs.

Please add code like this:
https://github.com/launchdarkly/go-client/compare/v4...Drahflow:v4#diff-969bed12664f4a5240245d483ad4e6afR216

**To reproduce**
Run launchdarkly client on a system on which will not be happy with launchdarkly's certificate chain, e.g. `alpine:3.7`.

**Expected behavior**
`err` variable should reach the logs.

**Logs**
Every 2 seconds:
```
{"@timestamp":"2019-06-21T09:51:44+0000","channel":"app","env":"development","host":"node-7fd55876c4-jzjp7","level":"info","msg":"Connecting to LaunchDarkly stream using URL: https://stream.launchdarkly.com/all","program":"..."}
```
but no indication of why the connection failed. After manually adding logging to my fork, reason was (but this was not part of the unmodified-SDK logs):
```
Get https://stream.launchdarkly.com/all: x509: certificate signed by unknown authority
```

**SDK version**
v4

**Comment by bwoskow-ld** [comment]
Thanks for the feedback, Drahflow! We'll take a look at this.

While I have your attention, I also want to point you to https://github.com/launchdarkly/go-server-sdk which is where we're now maintaining the Go SDK. Per [this note](https://github.com/launchdarkly/go-client/blob/v4/CHANGELOG.md#note-on-future-releases) all future changes (including the potential fix for this improvement) will be in that repository.

**Comment by bwoskow-ld** [comment]
I added a logged message as you suggested. It'll be available in the next version of the Go SDK (version 4.8.2).
